repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: trailing-whitespace
  - id: check-yaml
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
- repo: local
  hooks:
  - id: django-test
    name: Django Test Runner
    entry: python manage.py test
    always_run : true
    pass_filenames: false
    language: system
